# Use an official Python runtime as a parent image
FROM python:3

# Set the working directory in the container
WORKDIR /app

# Copy the client script into the container
COPY Client.py /app

# Run the client script
CMD ["python", "Client.py"]
